name: deploy-build-testing

on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Version
        run: docker version

      - name: Settings
        run: echo APP_BUILD_TARGET=deploy > .env

      - name: Build Docker Images
        run: docker compose build app
